#############################################################################
# Makefile for building: bin/kea-landscape-tool
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  kea-landscape-tool.pro
# Template: app
# Command: /home/diego/lib/Qt5.8.0/5.8/gcc_64/bin/qmake -o Makefile kea-landscape-tool.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../lib/soplex-3.0.0/src -I../../lib/Qt5.8.0/5.8/gcc_64/include -I../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets -I../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui -I../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /home/diego/lib/Qt5.8.0/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = kea-landscape-tool1.0.0
DISTDIR = /home/diego/Projects/kea-landscape-tool/.tmp/kea-landscape-tool1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/diego/lib/Qt5.8.0/5.8/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/diego/Projects/kea-landscape-tool/../../lib/soplex-3.0.0/lib/ -lsoplex -lz -lgmp -L/home/diego/lib/Qt5.8.0/5.8/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		kea-landscape-tool.pro src/mainwindow.h src/main.cpp \
		src/mainwindow.cpp
QMAKE_TARGET  = kea-landscape-tool
DESTDIR       = bin/
TARGET        = bin/kea-landscape-tool


first: all
####### Build rules

$(TARGET): /home/diego/Projects/kea-landscape-tool/../../lib/soplex-3.0.0/lib/libsoplex.a ui_mainwindow.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kea-landscape-tool.pro ../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf ../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		kea-landscape-tool.pro \
		../../lib/Qt5.8.0/5.8/gcc_64/lib/libQt5Widgets.prl \
		../../lib/Qt5.8.0/5.8/gcc_64/lib/libQt5Gui.prl \
		../../lib/Qt5.8.0/5.8/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile kea-landscape-tool.pro
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf:
../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf:
kea-landscape-tool.pro:
../../lib/Qt5.8.0/5.8/gcc_64/lib/libQt5Widgets.prl:
../../lib/Qt5.8.0/5.8/gcc_64/lib/libQt5Gui.prl:
../../lib/Qt5.8.0/5.8/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile kea-landscape-tool.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../lib/Qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QMainWindow \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qicon.h \
		src/mainwindow.h \
		moc_predefs.h \
		../../lib/Qt5.8.0/5.8/gcc_64/bin/moc
	/home/diego/lib/Qt5.8.0/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/diego/lib/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++ -I/home/diego/Projects/kea-landscape-tool -I/home/diego/lib/soplex-3.0.0/src -I/home/diego/lib/Qt5.8.0/5.8/gcc_64/include -I/home/diego/lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets -I/home/diego/lib/Qt5.8.0/5.8/gcc_64/include/QtGui -I/home/diego/lib/Qt5.8.0/5.8/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: src/mainwindow.ui \
		../../lib/Qt5.8.0/5.8/gcc_64/bin/uic
	/home/diego/lib/Qt5.8.0/5.8/gcc_64/bin/uic src/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QMainWindow \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qicon.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QApplication \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qapplication.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qeventloop.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qguiapplication.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qinputmethod.h \
		../../lib/soplex-3.0.0/src/soplex.h \
		../../lib/soplex-3.0.0/src/spxdefines.h \
		../../lib/soplex-3.0.0/src/basevectors.h \
		../../lib/soplex-3.0.0/src/rational.h \
		../../lib/soplex-3.0.0/src/idlist.h \
		../../lib/soplex-3.0.0/src/islist.h \
		../../lib/soplex-3.0.0/src/vectorbase.h \
		../../lib/soplex-3.0.0/src/dvectorbase.h \
		../../lib/soplex-3.0.0/src/spxalloc.h \
		../../lib/soplex-3.0.0/src/spxout.h \
		../../lib/soplex-3.0.0/src/exceptions.h \
		../../lib/soplex-3.0.0/src/ssvectorbase.h \
		../../lib/soplex-3.0.0/src/idxset.h \
		../../lib/soplex-3.0.0/src/svectorbase.h \
		../../lib/soplex-3.0.0/src/dsvectorbase.h \
		../../lib/soplex-3.0.0/src/unitvectorbase.h \
		../../lib/soplex-3.0.0/src/svsetbase.h \
		../../lib/soplex-3.0.0/src/classarray.h \
		../../lib/soplex-3.0.0/src/dataset.h \
		../../lib/soplex-3.0.0/src/dataarray.h \
		../../lib/soplex-3.0.0/src/datakey.h \
		../../lib/soplex-3.0.0/src/spxsolver.h \
		../../lib/soplex-3.0.0/src/timer.h \
		../../lib/soplex-3.0.0/src/timerfactory.h \
		../../lib/soplex-3.0.0/src/notimer.h \
		../../lib/soplex-3.0.0/src/usertimer.h \
		../../lib/soplex-3.0.0/src/wallclocktimer.h \
		../../lib/soplex-3.0.0/src/spxlp.h \
		../../lib/soplex-3.0.0/src/spxlpbase.h \
		../../lib/soplex-3.0.0/src/spxid.h \
		../../lib/soplex-3.0.0/src/lprowbase.h \
		../../lib/soplex-3.0.0/src/lpcolbase.h \
		../../lib/soplex-3.0.0/src/lprowsetbase.h \
		../../lib/soplex-3.0.0/src/lpcolsetbase.h \
		../../lib/soplex-3.0.0/src/nameset.h \
		../../lib/soplex-3.0.0/src/datahashtable.h \
		../../lib/soplex-3.0.0/src/didxset.h \
		../../lib/soplex-3.0.0/src/spxfileio.h \
		../../lib/soplex-3.0.0/src/gzstream.h \
		../../lib/soplex-3.0.0/src/spxscaler.h \
		../../lib/soplex-3.0.0/src/vector.h \
		../../lib/soplex-3.0.0/src/svector.h \
		../../lib/soplex-3.0.0/src/svset.h \
		../../lib/soplex-3.0.0/src/dsvector.h \
		../../lib/soplex-3.0.0/src/dvector.h \
		../../lib/soplex-3.0.0/src/lprowset.h \
		../../lib/soplex-3.0.0/src/lpcolset.h \
		../../lib/soplex-3.0.0/src/lprow.h \
		../../lib/soplex-3.0.0/src/lpcol.h \
		../../lib/soplex-3.0.0/src/spxbasis.h \
		../../lib/soplex-3.0.0/src/ssvector.h \
		../../lib/soplex-3.0.0/src/slinsolver.h \
		../../lib/soplex-3.0.0/src/array.h \
		../../lib/soplex-3.0.0/src/random.h \
		../../lib/soplex-3.0.0/src/unitvector.h \
		../../lib/soplex-3.0.0/src/updatevector.h \
		../../lib/soplex-3.0.0/src/slufactor.h \
		../../lib/soplex-3.0.0/src/clufactor.h \
		../../lib/soplex-3.0.0/src/slufactor_rational.h \
		../../lib/soplex-3.0.0/src/slinsolver_rational.h \
		../../lib/soplex-3.0.0/src/clufactor_rational.h \
		../../lib/soplex-3.0.0/src/spxsimplifier.h \
		../../lib/soplex-3.0.0/src/spxmainsm.h \
		../../lib/soplex-3.0.0/src/spxequilisc.h \
		../../lib/soplex-3.0.0/src/spxleastsqsc.h \
		../../lib/soplex-3.0.0/src/spxgeometsc.h \
		../../lib/soplex-3.0.0/src/spxstarter.h \
		../../lib/soplex-3.0.0/src/spxweightst.h \
		../../lib/soplex-3.0.0/src/spxsumst.h \
		../../lib/soplex-3.0.0/src/spxvectorst.h \
		../../lib/soplex-3.0.0/src/spxpricer.h \
		../../lib/soplex-3.0.0/src/sorter.h \
		../../lib/soplex-3.0.0/src/spxautopr.h \
		../../lib/soplex-3.0.0/src/spxdevexpr.h \
		../../lib/soplex-3.0.0/src/spxsteeppr.h \
		../../lib/soplex-3.0.0/src/spxsteepexpr.h \
		../../lib/soplex-3.0.0/src/spxdantzigpr.h \
		../../lib/soplex-3.0.0/src/spxparmultpr.h \
		../../lib/soplex-3.0.0/src/spxhybridpr.h \
		../../lib/soplex-3.0.0/src/spxratiotester.h \
		../../lib/soplex-3.0.0/src/spxdefaultrt.h \
		../../lib/soplex-3.0.0/src/spxharrisrt.h \
		../../lib/soplex-3.0.0/src/spxfastrt.h \
		../../lib/soplex-3.0.0/src/spxboundflippingrt.h \
		../../lib/soplex-3.0.0/src/sol.h \
		../../lib/soplex-3.0.0/src/solbase.h \
		../../lib/soplex-3.0.0/src/soplexlegacy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QMainWindow \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qicon.h \
		ui_mainwindow.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/QVariant \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QAction \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qaction.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qactiongroup.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QApplication \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qapplication.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qeventloop.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qguiapplication.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qinputmethod.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QButtonGroup \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QHeaderView \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qheaderview.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qframe.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qstyleoption.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtGui/qvalidator.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtCore/qregularexpression.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qslider.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractslider.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qstyle.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabbar.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qrubberband.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QMenuBar \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qmenubar.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qmenu.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QStatusBar \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qstatusbar.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QToolBar \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtoolbar.h \
		../../lib/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

